root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true

login:
    pattern: /login
    defaults: { _controller: AcmePASBundle:Security:login }

login_check:
    pattern: /login_check
    
logout:
    pattern: /logout

pas_homepage:
    pattern: /home
    defaults: { _controller: AcmePASBundle:Home:home }

pas_budget_request_form:
    pattern: /budget-request
    defaults: { _controller: AcmePASBundle:BudgetRequest:budgetRequest }

pas_budget_request_status:
    pattern: /budget-request-review
    defaults: { _controller: AcmePASBundle:BudgetRequestStatus:budgetRequestReview }

pas_budget_confirmation_form:
    pattern: /budget-confirm
    defaults: { _controller: AcmePASBundle:BudgetConfirmation:budgetConfirm }

pas_budget_requests_list:
    pattern: /budget-requests-list
    defaults: { _controller: AcmePASBundle:BudgetRequestsList:budgetRequestsList }

pas_budget_check_form:
    pattern: /budget-check
    defaults: { _controller: AcmePASBundle:BudgetCheck:budgetCheck }

pas_pre_request_form:
    pattern: /pre-request
    defaults: { _controller: AcmePASBundle:PreRequest:preRequest }

pas_pre_request_status:
    pattern: /pre-request-review
    defaults: { _controller: AcmePASBundle:PreRequestStatus:preRequestReview }

pas_pre_approval_form:
    pattern: /pre-approve
    defaults: { _controller: AcmePASBundle:PreRequestApproval:preApprove }

pas_pre_requests_list:
    pattern: /pre-requests-list
    defaults: { _controller: AcmePASBundle:PreRequestsList:preRequestsList }

pas_post_request_form:
    pattern: /post-request
    defaults: { _controller: AcmePASBundle:PostRequest:postRequest }

pas_post_request_status:
    pattern: /post-request-review
    defaults: { _controller: AcmePASBundle:PostRequestStatus:postRequestReview }

pas_post_approval_form:
    pattern: /post-approve
    defaults: { _controller: AcmePASBundle:PostRequestApproval:postApprove }

pas_post_requests_list:
    pattern: /post-requests-list
    defaults: { _controller: AcmePASBundle:PostRequestsList:postRequestsList }

pas_success:
    pattern: /success
    defaults: { _controller: AcmePASBundle:Success:success }

pas_currency_rate:
    pattern: /currency_rate
    defaults: { _controller: AcmePASBundle:CurrencyRate:getRate }

pas_budget_exporting:
    pattern: /budget-export
    defaults: { _controller: AcmePASBundle:BudgetExporting:export }

pas_progress_exporting:
    pattern: /progress-export
    defaults: { _controller: AcmePASBundle:ProgressExporting:export }

pas_budget_requests_list_exporting:
    pattern: /budget-list-export
    defaults: { _controller: AcmePASBundle:BudgetRequestsListExporting:export }

pas_pre_requests_list_exporting:
    pattern: /pre-list-export
    defaults: { _controller: AcmePASBundle:PreRequestsListExporting:export }

pas_post_requests_list_exporting:
    pattern: /post-list-export
    defaults: { _controller: AcmePASBundle:PostRequestsListExporting:export }

pas_request_deletion:
    pattern: /request-delete
    defaults: { _controller: AcmePASBundle:RequestDeletion:delete }

pas_user:
    pattern: /user
    defaults: { _controller: AcmePASBundle:User:user }