parameters:
#    acme_pas.example.class: Acme\Bundle\PASBundle\Example

services:
#    acme_pas.example:
#        class: %acme_pas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
