parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: PAS
    database_user: caistudio
    database_password: culver
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: dc1c2fcbbdcb35691085fb7d2dd34d207
    database_path: null
