jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Acme\Bundle\PASBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: true
            iterations:       1

    role_hierarchy:
        ROLE_APPROVER:    ROLE_REQUESTER
        ROLE_CFO:         ROLE_APPROVER
        ROLE_USER:        [ROLE_REQUESTER, ROLE_APPROVER, ROLE_CFO]
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: AcmePASBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
        main:
            form_login:
                default_target_path: /home
                use_referer: true
            logout: ~
        secured_area:
            pattern:    ^/
            form_login: ~
            logout: ~

    access_control:
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/budget-request, roles: ROLE_REQUESTER }
        - { path: ^/budget-confirm, roles: ROLE_CFO }
        - { path: ^/pre-request, roles: ROLE_REQUESTER }
        - { path: ^/budget-check, roles: ROLE_REQUESTER }
        - { path: ^/pre-approve, roles: ROLE_APPROVER }
        - { path: ^/pre-request-review, roles: ROLE_REQUESTER }
        - { path: ^/post-request, roles: ROLE_REQUESTER }
        - { path: ^/post-approve, roles: ROLE_APPROVER }
        - { path: ^/post-request-review, roles: ROLE_REQUESTER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
